### ISSUE TITLE
Fix logstash client hosts

### ISSUE THREAD

**Issue by ShtykovaAA** [jgough/logstash-filter-opensearch#4]
I found that when I'm using hosts with `ssl=True` and also I had multiple workers then opensearch the client doesn't work properly

My logs: `https://{:host=>{:host=>{:host=>{:host=>{:host=>{:host=>{:host=>{:host=>{:host=>{:host=>{:host=>{:host=>{:host=>{:host=>{:host=>{:host=>{:host=>...`

PR to fix it: https://github.com/jgough/logstash-filter-opensearch/pull/3
Solution from [elasticsearch-plugin](https://github.com/logstash-plugins/logstash-filter-elasticsearch)

**Comment by jgough** [comment]
Thanks for the PR!

**Comment by ShtykovaAA** [comment]
Hi @jgough! Could please tell me if you have any opportunity to push new version to [rubegems](https://rubygems.org/gems/logstash-filter-opensearch)?

**Comment by jgough** [comment]
Hey, try that now!  Thanks for your help fixing this issue.

**Comment by ShtykovaAA** [comment]
it works, thank you!
